services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\Daycarecenters\:
    resource: '../Classes/*'

  JWeiland\Daycarecenters\Configuration\ExtConf:
    public: true

  JWeiland\Daycarecenters\EventListener\AddPaginatorEventListener:
    tags:
    - name: event.listener
      event: JWeiland\Daycarecenters\Event\PostProcessFluidVariablesEvent

  JWeiland\Daycarecenters\EventListener\SetDefaultCategoryToPOIEventListener:
    tags:
    - name: event.listener
      event: JWeiland\Maps2\Event\PostProcessPoiCollectionRecordEvent

